#!/bin/zsh

bar_position        : top
height              : 20
vertical_padding    : 8
horizontal_padding  : 100
text_padding        : 0
border              : true
border_width        : 0
background_colour   : #121212
foreground_colour   : #ffd1dc
border_colour       : #000000
font                : JetBrainsMono Nerd Font
font_size           : 12

# modules

module.0.name       : windows
module.0.cmd        : ~/.config/sxbar/scripts/windows.sh
module.0.enabled    : true
module.0.interval   : 2
module.0.position   : center

module.1.name       : clock
module.1.cmd        : echo -n "  " && date '+%H:%M'
module.1.enabled    : true
module.1.interval   : 1

module.2.name       : volume
module.2.cmd        : vol=$(amixer get Master | awk -F'[][]' 'END{print $2}'); echo -n "  $vol"
module.2.enabled    : true
module.2.interval   : 1

module.3.name       : cpu
module.3.cmd        : top -bn1 | grep "Cpu(s)" | awk '{print "  " 100-$8 "%"}'
module.3.enabled    : true
module.3.interval   : 3
module.3.position   : left

module.4.name       : ram
module.4.cmd        : free -h | awk '/^Mem:/ {print "  "$3}'
module.4.enabled    : true
module.4.interval   : 5
module.4.position   : left

module.6.name       : battery
module.6.cmd        : BAT=$(cat /sys/class/power_supply/BAT1/capacity 2>/dev/null); STAT=$(cat /sys/class/power_supply/BAT1/status 2>/dev/null); echo -n "  $BAT%"
module.6.enabled    : true
module.6.interval   : 30

module.5.name        : network
module.5.cmd         : ~/.config/sxbar/scripts/network.sh
module.5.interval    : 2
module.5.enabled     : true

# special workspace configuration

workspaces.labels              : 󰣇 @ # $ %              
workspaces.active_background   : #ffd1dc
workspaces.active_foreground   : #121212
workspaces.inactive_background : #121212
workspaces.inactive_foreground : #ffd1dc
workspaces.padding_left        : 10
workspaces.padding_right       : 10
workspaces.spacing             : 0
workspaces.position            : left
